{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2019-05-17 11:27:36,174\tINFO node.py:469 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-05-17_11-27-36_2816/logs.\n",
      "2019-05-17 11:27:36,281\tINFO services.py:407 -- Waiting for redis server at 127.0.0.1:54692 to respond...\n",
      "2019-05-17 11:27:36,391\tINFO services.py:407 -- Waiting for redis server at 127.0.0.1:56748 to respond...\n",
      "2019-05-17 11:27:36,392\tINFO services.py:804 -- Starting Redis shard with 30.0 GB max memory.\n",
      "2019-05-17 11:27:36,403\tINFO node.py:483 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-05-17_11-27-36_2816/logs.\n",
      "2019-05-17 11:27:36,404\tWARNING services.py:1304 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 36878782464 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.\n",
      "2019-05-17 11:27:36,404\tINFO services.py:1427 -- Starting the Plasma object store with 70.0 GB memory using /tmp.\n",
      "/data/Github/shapeology_code/scripts/lib/utils.py:22: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.\n",
      "  self.D=yaml.load(open(yamlFile,'r'))\n",
      "/data/BstemAtlasDataBackup/ucsd_brain/CSHL_cells_dm/MD589/\n",
      "\u001b[2m\u001b[36m(pid=4434)\u001b[0m Amb_positive ALREADY EXIST\n",
      "\u001b[2m\u001b[36m(pid=4431)\u001b[0m LC 20005\n",
      "\u001b[2m\u001b[36m(pid=4434)\u001b[0m Amb 20019\n",
      "\u001b[2m\u001b[36m(pid=4431)\u001b[0m LC 40011\n",
      "\u001b[2m\u001b[36m(pid=4434)\u001b[0m Amb 40026\n",
      "\u001b[2m\u001b[36m(pid=4431)\u001b[0m LC 60016\n",
      "\u001b[2m\u001b[36m(pid=4434)\u001b[0m Amb 60017\n",
      "\u001b[2m\u001b[36m(pid=4431)\u001b[0m LC 80012\n",
      "\u001b[2m\u001b[36m(pid=4434)\u001b[0m Amb 80015\n",
      "\u001b[2m\u001b[36m(pid=4431)\u001b[0m LC 100019\n",
      "\u001b[2m\u001b[36m(pid=4431)\u001b[0m LC 2709 3615\n",
      "\u001b[2m\u001b[36m(pid=4434)\u001b[0m Amb 100000\n",
      "\u001b[2m\u001b[36m(pid=4434)\u001b[0m Amb 100028\n",
      "\u001b[2m\u001b[36m(pid=4434)\u001b[0m Amb 2968 5107\n",
      "\u001b[2m\u001b[36m(pid=4431)\u001b[0m LC 120018\n",
      "\u001b[2m\u001b[36m(pid=4434)\u001b[0m Amb 120025\n",
      "\u001b[2m\u001b[36m(pid=4431)\u001b[0m LC 132063\n",
      "\u001b[2m\u001b[36m(pid=4431)\u001b[0m LC_positive finished in 1506.2 seconds\n",
      "\u001b[2m\u001b[36m(pid=4434)\u001b[0m Amb 140021\n",
      "\u001b[2m\u001b[36m(pid=4431)\u001b[0m LC 20019\n",
      "\u001b[2m\u001b[36m(pid=4434)\u001b[0m Amb 160017\n",
      "\u001b[2m\u001b[36m(pid=4431)\u001b[0m LC 40003\n",
      "\u001b[2m\u001b[36m(pid=4431)\u001b[0m LC 40020\n",
      "\u001b[2m\u001b[36m(pid=4434)\u001b[0m Amb 172214\n",
      "Traceback (most recent call last):\n",
      "  File \"Cell_generator.py\", line 107, in <module>\n",
      "    ray.get([generator.remote(structure, cell_dir, patch_dir, stack, params) for structure in all_structures[(seq-1)*2:seq*2]])\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/ray/worker.py\", line 2184, in get\n",
      "    raise value\n",
      "ray.exceptions.RayWorkerError: The worker died unexpectedly while executing this task.\n",
      "2019-05-17 12:01:28,687\tERROR worker.py:1672 -- A worker died or was killed while executing task 00000000b234fdf6116950a618061085af054f36.\n"
     ]
    }
   ],
   "source": [
    "! python Cell_generator.py MD589 3 'shape_params-aws.yaml'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2019-05-17 12:17:24,414\tINFO node.py:469 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-05-17_12-17-24_567/logs.\n",
      "2019-05-17 12:17:24,520\tINFO services.py:407 -- Waiting for redis server at 127.0.0.1:31339 to respond...\n",
      "2019-05-17 12:17:24,630\tINFO services.py:407 -- Waiting for redis server at 127.0.0.1:44125 to respond...\n",
      "2019-05-17 12:17:24,631\tINFO services.py:804 -- Starting Redis shard with 30.0 GB max memory.\n",
      "2019-05-17 12:17:24,644\tINFO node.py:483 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-05-17_12-17-24_567/logs.\n",
      "2019-05-17 12:17:24,645\tWARNING services.py:1304 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 36878782464 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.\n",
      "2019-05-17 12:17:24,645\tINFO services.py:1427 -- Starting the Plasma object store with 70.0 GB memory using /tmp.\n",
      "/data/Github/shapeology_code/scripts/lib/utils.py:22: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.\n",
      "  self.D=yaml.load(open(yamlFile,'r'))\n",
      "/data/BstemAtlasDataBackup/ucsd_brain/CSHL_cells_dm/MD589/\n",
      "\u001b[2m\u001b[36m(pid=2298)\u001b[0m Tz 20\n",
      "\u001b[2m\u001b[36m(pid=2311)\u001b[0m VLL 20007\n",
      "\u001b[2m\u001b[36m(pid=2298)\u001b[0m Tz 20022\n",
      "\u001b[2m\u001b[36m(pid=2311)\u001b[0m VLL 40026\n",
      "\u001b[2m\u001b[36m(pid=2298)\u001b[0m Tz 40017\n",
      "\u001b[2m\u001b[36m(pid=2311)\u001b[0m VLL 60001\n",
      "\u001b[2m\u001b[36m(pid=2298)\u001b[0m Tz 60014\n",
      "\u001b[2m\u001b[36m(pid=2311)\u001b[0m VLL 80012\n",
      "\u001b[2m\u001b[36m(pid=2311)\u001b[0m VLL 100029\n",
      "\u001b[2m\u001b[36m(pid=2311)\u001b[0m VLL 2708 16388\n",
      "2019-05-17 12:35:07,689\tERROR worker.py:1609 -- Possible unhandled error from worker: \u001b[36mray_worker:__main__.generator()\u001b[39m (pid=2298, host=ip-172-31-29-217)\n",
      "  File \"Cell_generator.py\", line 62, in generator\n",
      "    extracted= extractor.extract_blobs(Stats,tile)\n",
      "  File \"/data/Github/shapeology_code/scripts/extractPatches.py\", line 115, in extract_blobs\n",
      "    self.computeDMs(extracted)\n",
      "  File \"/data/Github/shapeology_code/scripts/extractPatches.py\", line 151, in computeDMs\n",
      "    DMMat=self.DM.transform(asMat)\n",
      "  File \"/data/Github/shapeology_code/scripts/label_patch.py\", line 33, in transform\n",
      "    lowD=self.DM.transform(data1D)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/pydiffmap/diffusion_map.py\", line 247, in transform\n",
      "    return nystroem_oos(self, Y)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/pydiffmap/diffusion_map.py\", line 312, in nystroem_oos\n",
      "    kernel_extended = dmap_object.local_kernel.compute(Y)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/pydiffmap/kernel.py\", line 158, in compute\n",
      "    K = self._get_scaled_distance_mat(Y, y_bandwidths=y_bandwidths)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/pydiffmap/kernel.py\", line 168, in _get_scaled_distance_mat\n",
      "    dists = self.neigh.kneighbors_graph(Y, mode='distance')\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/sklearn/neighbors/base.py\", line 548, in kneighbors_graph\n",
      "    X, n_neighbors, return_distance=True)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/sklearn/neighbors/base.py\", line 443, in kneighbors\n",
      "    for s in gen_even_slices(X.shape[0], n_jobs)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py\", line 983, in __call__\n",
      "    if self.dispatch_one_batch(iterator):\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py\", line 825, in dispatch_one_batch\n",
      "    self._dispatch(tasks)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py\", line 782, in _dispatch\n",
      "    job = self._backend.apply_async(batch, callback=cb)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py\", line 222, in apply_async\n",
      "    return self._get_pool().apply_async(\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py\", line 363, in _get_pool\n",
      "    self._pool = ThreadPool(self._n_jobs)\n",
      "  File \"/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/pool.py\", line 828, in __init__\n",
      "    Pool.__init__(self, processes, initializer, initargs)\n",
      "  File \"/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/pool.py\", line 177, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/pool.py\", line 238, in _repopulate_pool\n",
      "    self._wrap_exception)\n",
      "  File \"/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/pool.py\", line 257, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/dummy/__init__.py\", line 51, in start\n",
      "    threading.Thread.start(self)\n",
      "  File \"/home/ubuntu/anaconda3/lib/python3.7/threading.py\", line 847, in start\n",
      "    _start_new_thread(self._bootstrap, ())\n",
      "RuntimeError: can't start new thread\n",
      "\n",
      "\u001b[2m\u001b[36m(pid=2311)\u001b[0m VLL 120019\n",
      "\u001b[2m\u001b[36m(pid=2311)\u001b[0m VLL 140022\n",
      "\u001b[2m\u001b[36m(pid=2311)\u001b[0m VLL 160018\n",
      "\u001b[2m\u001b[36m(pid=2311)\u001b[0m VLL 180005\n",
      "\u001b[2m\u001b[36m(pid=2311)\u001b[0m VLL 200007\n",
      "Traceback (most recent call last):\n",
      "  File \"Cell_generator.py\", line 107, in <module>\n",
      "    ray.get([generator.remote(structure, cell_dir, patch_dir, stack, params) for structure in all_structures[(seq-1)*2:seq*2]])\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/ray/worker.py\", line 2184, in get\n",
      "    raise value\n",
      "ray.exceptions.RayTaskError: \u001b[36mray_worker:__main__.generator()\u001b[39m (pid=2298, host=ip-172-31-29-217)\n",
      "  File \"Cell_generator.py\", line 62, in generator\n",
      "    extracted= extractor.extract_blobs(Stats,tile)\n",
      "  File \"/data/Github/shapeology_code/scripts/extractPatches.py\", line 115, in extract_blobs\n",
      "    self.computeDMs(extracted)\n",
      "  File \"/data/Github/shapeology_code/scripts/extractPatches.py\", line 151, in computeDMs\n",
      "    DMMat=self.DM.transform(asMat)\n",
      "  File \"/data/Github/shapeology_code/scripts/label_patch.py\", line 33, in transform\n",
      "    lowD=self.DM.transform(data1D)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/pydiffmap/diffusion_map.py\", line 247, in transform\n",
      "    return nystroem_oos(self, Y)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/pydiffmap/diffusion_map.py\", line 312, in nystroem_oos\n",
      "    kernel_extended = dmap_object.local_kernel.compute(Y)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/pydiffmap/kernel.py\", line 158, in compute\n",
      "    K = self._get_scaled_distance_mat(Y, y_bandwidths=y_bandwidths)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/pydiffmap/kernel.py\", line 168, in _get_scaled_distance_mat\n",
      "    dists = self.neigh.kneighbors_graph(Y, mode='distance')\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/sklearn/neighbors/base.py\", line 548, in kneighbors_graph\n",
      "    X, n_neighbors, return_distance=True)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/sklearn/neighbors/base.py\", line 443, in kneighbors\n",
      "    for s in gen_even_slices(X.shape[0], n_jobs)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py\", line 983, in __call__\n",
      "    if self.dispatch_one_batch(iterator):\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py\", line 825, in dispatch_one_batch\n",
      "    self._dispatch(tasks)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py\", line 782, in _dispatch\n",
      "    job = self._backend.apply_async(batch, callback=cb)\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py\", line 222, in apply_async\n",
      "    return self._get_pool().apply_async(\n",
      "  File \"/data/venv/shapeology_venv/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py\", line 363, in _get_pool\n",
      "    self._pool = ThreadPool(self._n_jobs)\n",
      "  File \"/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/pool.py\", line 828, in __init__\n",
      "    Pool.__init__(self, processes, initializer, initargs)\n",
      "  File \"/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/pool.py\", line 177, in __init__\n",
      "    self._repopulate_pool()\n",
      "  File \"/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/pool.py\", line 238, in _repopulate_pool\n",
      "    self._wrap_exception)\n",
      "  File \"/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/pool.py\", line 257, in _repopulate_pool_static\n",
      "    w.start()\n",
      "  File \"/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/dummy/__init__.py\", line 51, in start\n",
      "    threading.Thread.start(self)\n",
      "  File \"/home/ubuntu/anaconda3/lib/python3.7/threading.py\", line 847, in start\n",
      "    _start_new_thread(self._bootstrap, ())\n",
      "RuntimeError: can't start new thread\n",
      "\n"
     ]
    }
   ],
   "source": [
    "! python Cell_generator.py MD589 5 'shape_params-aws.yaml'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-05-17 10:23:27,353\tINFO node.py:469 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-05-17_10-23-27_23308/logs.\n",
      "2019-05-17 10:23:27,459\tINFO services.py:407 -- Waiting for redis server at 127.0.0.1:40289 to respond...\n",
      "2019-05-17 10:23:27,567\tINFO services.py:407 -- Waiting for redis server at 127.0.0.1:53403 to respond...\n",
      "2019-05-17 10:23:27,569\tINFO services.py:804 -- Starting Redis shard with 30.0 GB max memory.\n",
      "2019-05-17 10:23:27,578\tINFO node.py:483 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-05-17_10-23-27_23308/logs.\n",
      "2019-05-17 10:23:27,579\tWARNING services.py:1304 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 36878782464 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.\n",
      "2019-05-17 10:23:27,580\tINFO services.py:1427 -- Starting the Plasma object store with 70.0 GB memory using /tmp.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'node_ip_address': '172.31.29.217',\n",
       " 'redis_address': '172.31.29.217:40289',\n",
       " 'object_store_address': '/tmp/ray/session_2019-05-17_10-23-27_23308/sockets/plasma_store',\n",
       " 'raylet_socket_name': '/tmp/ray/session_2019-05-17_10-23-27_23308/sockets/raylet',\n",
       " 'webui_url': None}"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import ray\n",
    "ray.shutdown()\n",
    "ray.init(object_store_memory=70000000000,redis_max_memory=30000000000)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "shapeology",
   "language": "python",
   "name": "shapeology"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
